/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rbslmkjjzczsbboidcuk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic2xta2pqemN6c2Jib2lkY3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzI3MTgsImV4cCI6MjA3Nzc0ODcxOH0.EZ2GrQeMrpPhNh-vsrrag-wVh2M8Th8-B4y60u2qNa4"